export { default as FilePreview } from './FilePreview.vue'
export { default as ImagePreview } from './ImagePreview.vue'
export { default as VideoPreview } from './VideoPreview.vue'
export { default as AudioPreview } from './AudioPreview.vue'
export { default as PdfPreview } from './PdfPreview.vue'
export { default as CodePreview } from './CodePreview.vue'
export { default as TextPreview } from './TextPreview.vue'
